### ISSUE TITLE
just a couple of feature requests

### ISSUE THREAD

**Issue by boydkelly** [klakegg/docker-hugo#41]
Add .gitlab-ci.yaml examples/support
Add podman alternative build support

**Comment by sosiristseng** [comment]
As to `.gitlab-ci.yml` example, I got one from my example Hugo site: <https://gitlab.com/sosiristseng/template-hugo-clarity>

- `hugo:ext-alpine-ci` image
- gzip and brotli compression

```yaml
image: klakegg/hugo:ext-alpine-ci

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_BASE_URL: 'https://sosiristseng.gitlab.io/template-hugo-clarity/'

test:
  script:
  - hugo -b ${HUGO_BASE_URL}
  except:
  - main

pages:
  script:
  - apk add --update brotli
  - hugo --gc --minify -b ${HUGO_BASE_URL}
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
  only:
  - main
```
