### ISSUE TITLE
Invalid certs in busybox image

### ISSUE THREAD

**Issue by cbix** [klakegg/docker-hugo#62]
Thanks for the incredibly useful hugo images! I'm trying to create a simple (Drone) CI pipeline using the `klakegg/hugo:busybox` image that also does some simple tar.gz download and extraction before the hugo build: (this is from the `.drone.yml`, _not_ a hugo config)
```yml
- name: Build site
  image: klakegg/hugo:busybox
  commands:
    - mkdir -p .tmp/archive
    - wget -qO - https://example.com/archive.tar.gz | tar -xzC .tmp/archive
    - hugo
```
However `wget` (busybox) fails with a "Handshake failure" so I ran the same wget command in a plain busybox container and it worked as expected. After a quick investigation I noticed all the files under `/etc/ssl/certs` are symlinks to invalid locations.

I did not test if this also affects retrieving data from an https location in a Hugo template and I know I can work around this by running the wget in a separate step but nonetheless this should be fixed IMO ;)
