### ISSUE TITLE
Error: failed to download modules: binary with name "go" not found

### ISSUE THREAD

**Issue by hemna** [klakegg/docker-hugo#77]
Trying to standup my hugo instance with my docker-compose results in error not finding go

```
version: '3.2'

services:
  hugo:
    image: klakegg/hugo:0.101.0
    command: server
    container_name: hugo
    ports:
      - 1313:1313
    volumes:
      - /Users/i530566/devel/SAP/convergedcloud-opsdocu-ui:/src
```

```
└─> docker-compose up
[+] Running 5/5
 ⠿ hugo Pulled                                                                                                                               5.0s
   ⠿ fc0cda0e09ab Pull complete                                                                                                              0.6s
   ⠿ f0848786bdc8 Pull complete                                                                                                              3.3s
   ⠿ c65fcb485fc0 Pull complete                                                                                                              3.4s
   ⠿ 4f4fb700ef54 Pull complete                                                                                                              3.4s
[+] Running 1/1
 ⠿ Container hugo  Recreated                                                                                                                 0.2s
Attaching to hugo
hugo  | Error: failed to download modules: binary with name "go" not found
hugo exited with code 255
```
